// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fikra_dental/models/patient.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GenderAdapter());
    registerAdapter(PatientAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GenderAdapter());
    registerAdapter(PatientAdapter());
  }
}
