// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fikra_dental/models/account.dart';
import 'package:fikra_dental/models/appointment.dart';
import 'package:fikra_dental/models/doctor.dart';
import 'package:fikra_dental/models/patient.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AppointmentAdapter());
    registerAdapter(AppointmentStatusAdapter());
    registerAdapter(DoctorAdapter());
    registerAdapter(DoctorScheduleAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(PatientAdapter());
    registerAdapter(WeekDayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AppointmentAdapter());
    registerAdapter(AppointmentStatusAdapter());
    registerAdapter(DoctorAdapter());
    registerAdapter(DoctorScheduleAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(PatientAdapter());
    registerAdapter(WeekDayAdapter());
  }
}
